default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.7456
    has_acceleration_limits: true
    max_acceleration: 1.862112371057039
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.5713
    has_acceleration_limits: true
    max_acceleration: 1.8075463016219946
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.5711
    has_acceleration_limits: true
    max_acceleration: 3.7395568038464284
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.0947
    has_acceleration_limits: true
    max_acceleration: 4.184796723604036
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.0938
    has_acceleration_limits: true
    max_acceleration: 4.255777556454399
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 2.7844
    has_acceleration_limits: true
    max_acceleration: 4.091516905940958
    has_jerk: false
