default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.7976891295541595
    has_acceleration_limits: true
    max_acceleration: 1.5076999142030323
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.6406094968746698
    has_acceleration_limits: true
    max_acceleration: 0.643365435800682
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: true
    max_acceleration: 1.7066963864945546
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.9670597283903604
    has_acceleration_limits: true
    max_acceleration: 5.061468327329231
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.251474735072685
    has_acceleration_limits: true
    max_acceleration: 5.143585062168162
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.595378259108319
    has_acceleration_limits: true
    max_acceleration: 6.231994863300119
    has_jerk: false
