default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.150151891130808
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.9670597283903604
    has_acceleration_limits: true
    max_acceleration: 1.4128855849477908
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.537856055185257
    has_acceleration_limits: true
    max_acceleration: 2.5210311417695874
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.504915783575617
    has_acceleration_limits: true
    max_acceleration: 97.4664387477353
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 182.65073567382518
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 12.566370614359172
    has_acceleration_limits: true
    max_acceleration: 100.53096491487338
    has_jerk: false
