default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.83972435438753
    has_acceleration_limits: true
    max_acceleration: 12.76953344640725
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.66519142918809
    has_acceleration_limits: true
    max_acceleration: 9.928064409333242
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.71238898038469
    has_acceleration_limits: true
    max_acceleration: 6.969378109575402
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.50491578357562
    has_acceleration_limits: true
    max_acceleration: 47.68925519016255
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.50491578357562
    has_acceleration_limits: true
    max_acceleration: 48.953076912202526
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.9706410125358
    has_acceleration_limits: true
    max_acceleration: 214.93590012478643
    has_jerk: false
