/platform/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    velocity_command_controller:
      type: forward_command_controller/ForwardCommandController
    position_command_controller:
        type: forward_command_controller/ForwardCommandController
/platform/velocity_command_controller:
  ros__parameters:
    joints:
    - move_x
    - move_theta
    interface_name: velocity
/platform/position_command_controller:
  ros__parameters:
    joints:
    - pillar1
    - pillar2
    - pillar3
    - pillar4
    - shield
    interface_name: position
