name: ROS-Industrial CI
run-name: ROS-Industrial CI - ${{ github.event_name }}

on:
  push:
    branches:
      - master
      - feature/**
      - fix/**

  # When there is a pull request against master
  pull_request:
    branches:
      - master
      - feature/**
      - fix/**

  schedule:
    # Run every Monday at 1PM UTC
    - cron: 0 13 * * 1

jobs:
  industrial_ci:
    name: ROS-Industrial CI
    strategy:
      matrix:
        env:
        - ROS_REPO: ros
          BUILDER: colcon
          ROS_DISTRO: jazzy
          BEFORE_TEST_HOOK: ./after_build_hook.sh
    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
      EVENT_NAME: ${{ github.event_name }}
      BRANCH: ${{ github.event.ref }}
      PR_BRANCH: ${{ github.event.pull_request.head.ref }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_NUMBER: ${{ github.event.number }}
      ANALYZER_TOKEN: ${{ secrets.ANALYZER_TOKEN }}
      DEBUG_BASH: true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - name: Make hook script executable
        run: chmod +x ./after_build_hook.sh
      - uses: 'kroshu/industrial_ci@master'
        env: ${{ matrix.env }}
