default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.236
    has_acceleration_limits: true
    max_acceleration: 10.0643
    has_jerk_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: true
    max_acceleration: 1.72
    has_jerk_limits: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.7596
    has_acceleration_limits: true
    max_acceleration: 2.6983
    has_jerk_limits: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: true
    max_acceleration: 56.544
    has_jerk_limits: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: true
    max_acceleration: 49.3066
    has_jerk_limits: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 7.5573
    has_acceleration_limits: true
    max_acceleration: 125.4542
    has_jerk_limits: false
