default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: true
    max_acceleration: 22.7931
    has_jerk_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.236
    has_acceleration_limits: true
    max_acceleration: 6.6208
    has_jerk_limits: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: true
    max_acceleration: 24.4228
    has_jerk_limits: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: true
    max_acceleration: 122.6388
    has_jerk_limits: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: true
    max_acceleration: 118.989
    has_jerk_limits: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 9.4248
    has_acceleration_limits: true
    max_acceleration: 237.1514
    has_jerk_limits: false
