default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 19.759143568083427
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.235987755982989
    has_acceleration_limits: true
    max_acceleration: 4.788975414071335
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 11.369007853738777
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 143.61881961056037
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.853981633974483
    has_acceleration_limits: true
    max_acceleration: 117.51416402978569
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 9.42477796076938
    has_acceleration_limits: true
    max_acceleration: 237.15063943642176
    has_jerk: false
