# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    max_position: 2.96706
    min_position: -2.96706
    has_velocity_limits: true
    max_velocity: 6.28318
    has_acceleration_limits: true
    max_acceleration: 22.78828
  joint_2:
    max_position: 0.78539
    min_position: -3.31612
    has_velocity_limits: true
    max_velocity: 5.23598
    has_acceleration_limits: true
    max_acceleration: 6.61769
  joint_3:
    max_position: 2.7
    min_position: -2.09439
    has_velocity_limits: true
    max_velocity: 6.28318
    has_acceleration_limits: true
    max_acceleration: 24.40545
  joint_4:
    max_position: 3.22885
    min_position: -3.22885
    has_velocity_limits: true
    max_velocity: 7.85398
    has_acceleration_limits: true
    max_acceleration: 122.50790
  joint_5:
    max_position: 2.09439
    min_position: -2.09439
    has_velocity_limits: true
    max_velocity: 7.85398
    has_acceleration_limits: true
    max_acceleration: 126.29010
  joint_6:
    max_position: 6.10865
    min_position: -6.10865
    has_velocity_limits: true
    max_velocity: 9.42477
    has_acceleration_limits: true
    max_acceleration: 284.56455
