lbriiwa7:
  # Publish all joint states ----------------------------------- 
  joint_state_controller: 
    type: joint_state_controller/JointStateController 
    publish_rate: 50 

  # Position Controllers --------------------------------------- 
  LBRiiwa7Joint1_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint1 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint2_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint2 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint3_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint3 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint4_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint4 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint5_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint5 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint6_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint6 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint7_position_controller: 
    type: effort_controllers/JointPositionController 
    joint: LBRiiwa7Joint7 
    pid: {p: 100, i: 0.01, d: 10} 

  # Effort Controllers --------------------------------------- 
  LBRiiwa7Joint1_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint1 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint2_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint2 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint3_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint3 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint4_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint4 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint5_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint5 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint6_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint6 
    pid: {p: 100, i: 0.01, d: 10} 
  LBRiiwa7Joint7_torque_controller: 
    type: effort_controllers/JointEffortController 
    joint: LBRiiwa7Joint7 
    pid: {p: 100, i: 0.01, d: 10} 

